services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: HouseForPets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pipi2014pupu
    ports:
      - "5232:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ./ 
      dockerfile: Dockerfile 
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=HouseForPets;Username=postgres;Password=pipi2014pupu
      - Redis__Host=redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:8080"
    environment:
      - NODE_ENV=production
      - VUE_APP_API_URL=http://localhost:7054
    depends_on:
      - backend
    restart: unless-stopped


volumes:
  redis_data:
  postgres_data: